name: ci
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    name: test
    env:
      RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: rustup toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: cargo install just
      uses: baptiste0928/cargo-install@v3
      with:
        crate: just
        version: '1.34.0'

    - name: System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libdrm-dev \
            libgbm-dev \
            libinput-dev \
            libseat-dev \
            libsystemd-dev \
            libudev-dev \
            libwayland-dev \
            libxkbcommon-dev

    - run: cargo test

  check-strict:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: rustup toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt,clippy

    - name: cargo install just
      uses: baptiste0928/cargo-install@v3
      with:
        crate: just
        version: '1.34.0'

    - name: System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libdrm-dev \
            libgbm-dev \
            libinput-dev \
            libseat-dev \
            libsystemd-dev \
            libudev-dev \
            libwayland-dev \
            libxkbcommon-dev

    - run: just check-strict

  check-doc:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: rustup toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt,clippy

    - name: System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libdrm-dev \
            libgbm-dev \
            libinput-dev \
            libseat-dev \
            libsystemd-dev \
            libudev-dev \
            libwayland-dev \
            libxkbcommon-dev

    - name: Check documentation
      run: RUSTDOCFLAGS='-D warnings' cargo doc --no-deps --document-private-items --workspace
